# Generated by Django 4.2.6 on 2023-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
